GET http://localhost:3001/api/blogs/1

###

GET http://localhost:3001/api/blogs/1000

###

GET http://localhost:3001/api/users/teukka@hotmail.com

###

GET http://localhost:3001/api/users/non-existing-user

###

GET http://localhost:3001/api/users/pave@hotmail.com

###

GET http://localhost:3001/api/users/teukka@hotmail.com?read=false