POST http://localhost:3001/api/blogs/ HTTP/1.1 
content-type: application/json

{ "title": "Added blog 2",
  "url": "www.google.com",
  "author": "Matias Mäkynen",
  "likes": 1
}

###


POST http://localhost:3001/api/blogs/ HTTP/1.1 
content-type: application/json

{ "title": "Added blog",
  "author": "Matias Mäkynen",
  "likes": 1
}

###

POST http://localhost:3001/api/blogs/ HTTP/1.1 
content-type: application/json

{ "title": null,
  "url": "www.google.com",
  "author": "Matias Mäkynen",
  "likes": 1
}


###

POST http://localhost:3001/api/users/ HTTP/1.1 
content-type: application/json

{ "name": "Teuvo Hakkarainen",
  "username": "superuser"
}

###


POST http://localhost:3001/api/users/ HTTP/1.1 
content-type: application/json

{ "name": "Teuvo Hakkarainen"
}

###

POST http://localhost:3001/api/users/ HTTP/1.1 
content-type: application/json

{ "name": "Teuvo Hakkarainen",
  "username": "teukka@hotmail.com"
}

###


POST http://localhost:3001/api/users/ HTTP/1.1 
content-type: application/json

{ "name": "Paavo Väyrynen",
  "username": "pave@hotmail.com"
}

###


POST http://localhost:3001/api/blogs/ HTTP/1.1 
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRldWtrYUBob3RtYWlsLmNvbSIsImlkIjoyLCJpYXQiOjE3MDczOTEzOTl9.LBKquLo0uncMYtkGIbhpagY5yterrh9vQEmv3YJfmUQ


{ "title": "Added blog 4",
  "url": "www.google.com",
  "author": "Matias Mäkynen",
  "likes": 1
}

###

POST http://localhost:3001/api/blogs/ HTTP/1.1 
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRldWtrYUBob3RtYWlsLmNvbSIsImlkIjoxLCJpYXQiOjE3MDc2NDU0MTd9.UlKR6j9Y88wR79GMBgeX_cOJOZl_QEA6_sNTfdKRPEI


{ "title": "normal blog",
  "url": "www.google.com",
  "author": "Ghost writer",
  "likes": 2,
  "year": 2025
}

