PUT http://localhost:3001/api/blogs/1

###

PUT http://localhost:3001/api/blogs/250


###

PUT http://localhost:3001/api/users/non-existing-user HTTP/1.1 
content-type: application/json

{ "username": "hyperuser" }

###

PUT http://localhost:3001/api/users/hyperuser HTTP/1.1 
content-type: application/json

{ "username": "superuser"
}

###

PUT http://localhost:3001/api/users/superuser HTTP/1.1 
content-type: application/json

{ "username": "hyperuser"
}

###

PUT http://localhost:3001/api/users/superuser HTTP/1.1 



###

PUT http://localhost:3001/api/readinglists/2 HTTP/1.1 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRldWtrYUBob3RtYWlsLmNvbSIsImlkIjoxLCJpYXQiOjE3MDc2NTIyNDd9.wywpOlwg1E98Y1tZoIQmW9WJeaJA07W8PVHB-gfz_z8
content-type: application/json

{ "read": "false"
}